baseURL = "https://nrelabs.io/"
languageCode = "en-us"
theme = "nre-hugo-theme"
googleAnalytics = "UA-120903857-1"
title = "NRE Labs"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  post = "/:year/:month/:title/"

[params]
  author = "The NRE Team"
  githubUsername = "nre-learning"
  accent = "red"
  showBorder = true
  backgroundColor = "white"
  font = "Roboto"
  highlight = true
  highlightStyle = "solarized-dark"
  highlightLanguages = ["go", "python", "haskell", "kotlin", "scala", "swift"]
  favicon = ""
  description = "Making Networks More Reliable Through Automation"
  background_color_class = "bg-black"

[outputs]
home = ["HTML", "AMP", "RSS"]
page = ["HTML"]

[[menu.social]]
    name = "Forums"
    url = "https://discuss.nrelabs.io/"
    weight = 1

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/nrelabs"
    weight = 2

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/nre-learning"
    weight = 3

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCbfZq3sDGx6gmv7KRrhRh4g"
    weight = 4

[[menu.main]]
    identifier = "about"
    url = "/about/"
    name = "About"
    weight = 5

[[menu.main]]
    identifier = "community"
    url = "/community/"
    name = "Community"
    weight = 10

[[menu.main]]
    identifier = "resources"
    url = "/resources/"
    name = "Resources"
    weight = 15

[[menu.main]]
    identifier = "post"
    url = "/post/"
    name = "Blogs"
    weight = 20

[outputFormats]
[outputFormats.HTML]
mediaType = "text/html"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"